USE GeorgiaTechLibrary;

-- Disable foreign key constraints
ALTER TABLE Loan NOCHECK CONSTRAINT ALL;
ALTER TABLE [Member] NOCHECK CONSTRAINT ALL;
ALTER TABLE Staff NOCHECK CONSTRAINT ALL;
ALTER TABLE [User] NOCHECK CONSTRAINT ALL;
ALTER TABLE DigitalItemLibrary NOCHECK CONSTRAINT ALL;
ALTER TABLE DigitalItemAuthor NOCHECK CONSTRAINT ALL;
ALTER TABLE BookInstance NOCHECK CONSTRAINT ALL;
ALTER TABLE BookAuthor NOCHECK CONSTRAINT ALL;

-- Delete data from the tables in the correct order to avoid foreign key conflicts
DELETE FROM Loan;
DELETE FROM [Member];
DELETE FROM Staff;
DELETE FROM [User];
DELETE FROM DigitalItemLibrary;
DELETE FROM DigitalItemAuthor;
DELETE FROM DigitalItem;
DELETE FROM BookInstance;
DELETE FROM BookAuthor;
DELETE FROM Book;
DELETE FROM [Library];

-- Re-enable foreign key constraints
ALTER TABLE Loan CHECK CONSTRAINT ALL;
ALTER TABLE [Member] CHECK CONSTRAINT ALL;
ALTER TABLE Staff CHECK CONSTRAINT ALL;
ALTER TABLE [User] CHECK CONSTRAINT ALL;
ALTER TABLE DigitalItemLibrary CHECK CONSTRAINT ALL;
ALTER TABLE DigitalItemAuthor CHECK CONSTRAINT ALL;
ALTER TABLE BookInstance CHECK CONSTRAINT ALL;
ALTER TABLE BookAuthor CHECK CONSTRAINT ALL;
