name: .NET Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format

    - name: Restore dependencies
      run: dotnet restore GeorgiaTechLibrary/GeorgiaTechLibrary.sln

    - name: Format code
      run: dotnet format GeorgiaTechLibrary/GeorgiaTechLibrary.sln --check --severity info

    - name: Build
      run: dotnet build --configuration Release GeorgiaTechLibrary/GeorgiaTechLibrary.sln --no-restore

    - name: Run Roslyn Analyzers
      run: dotnet build GeorgiaTechLibrary/GeorgiaTechLibrary.sln --configuration Release

    - name: Run tests and collect coverage
      run: |
        dotnet test GeorgiaTechLibrary/GeorgiaTechLibrary.sln --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --filter FullyQualifiedName~GeorgiaTechLibraryTest.IntegrationTests
        reportgenerator "-reports:coverage.opencover.xml" "-targetdir:coveragereport" "-reporttypes:Html"

    - name: Install Postman CLI
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

    - name: Login to Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

    - name: Run API tests
      run: postman collection run "23729163-05e51c4a-af3d-4cee-ad64-62ea04b07f80"
